name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: MSBuild
      working-directory: ./
      run: msbuild Bieberiser.sln /t:Restore /t:Rebuild /P:Configuration=Release
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: Bieberiser
        # Directory containing files to upload
        path: ./Bieberiser/bin/Release/net48
